### PR TITLE
Smart/smart main2

### PR DESCRIPTION
**Pull request by XcrigX**
Update to base project master (at HAPI v6.4), and refactor to to utilize the new custom-bean-packages and custom-interceptor-classes properties to scan for config/beans and discover the interceptors. 
I had two main goals with this update (1) get up to date with the latest HAPI release, and (2) reduce possible conflicts with the base jpa-starter project to make future merges more straight-forward. 

There should now only be 3 files which clash with the JPA starter:
 - .github/workflows/maven.yml - to enable the -Pboot profile
 - POM.xml - add springboot-security and other dependencies
 - src/test/resources/application.yml - to disable spring security auto configuration so the non-smart tests will work

NOTE: I haven't yet deployed and functionally tested this, will be doing that over the next few days - so there could be additional updates needed.

### CODE REVIEW

**Comment by jkiddo** [comment]
Sounds great! Let me know how the testing of it goes and I'll be happy to merge it in!

**Comment by jkiddo** [comment]
@XcrigX any updates?

**Comment by XcrigX** [comment]
Apologies - I've been out of office recently. So far it looks good to me. I've run it through Touchstone BB-Carin test suites and passed the tests there - and with my own manual testing everything is working.  NOTE that since most of the SMART-specific items were pulled out of the classpath application.yaml - you may have to explicitly configure more things if you deploy it. The application-smart.yaml file contains basically that set of elements that will need to be configured for deployment.

**Comment by haiderghaleb** [comment]
Hello @XcrigX, I'm trying to find application-smart.yaml but can't get it also tried to implement the smart on FHIR but didn't work

**Pull request merged**
